# Generated by Django 4.2.7 on 2025-09-19 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Duyuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                ("kategori", models.CharField(max_length=100, verbose_name="Kategori")),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("onemli", "Önemli"),
                            ("acil", "Acil"),
                            ("bilgi", "Bilgi"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                ("ozet", models.TextField(max_length=500, verbose_name="Özet")),
                ("detaylar", models.TextField(verbose_name="Detaylar")),
                (
                    "resim",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="duyurular/resimler/",
                        verbose_name="Resim",
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "yayinlandi",
                    models.BooleanField(default=False, verbose_name="Yayınlandı"),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "Duyurular",
                "ordering": ["-sira", "-tarih"],
            },
        ),
    ]
