# Generated by Django 4.2.7 on 2025-09-19 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TahsilatSorgu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sorgu_tipi",
                    models.CharField(
                        choices=[("TCKN", "TC Kimlik No"), ("VKN", "Vergi Kimlik No")],
                        max_length=4,
                    ),
                ),
                (
                    "sorgu_degeri",
                    models.CharField(help_text="TCKN veya VKN", max_length=20),
                ),
                ("baslangic_tarihi", models.DateTimeField(blank=True, null=True)),
                ("bitis_tarihi", models.DateTimeField(blank=True, null=True)),
                ("sadece_odenmemis", models.BooleanField(default=False)),
                (
                    "sorgu_tarihi",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("basarili", models.BooleanField(default=True)),
                ("hata_mesaji", models.TextField(blank=True, null=True)),
                ("donen_kayit_sayisi", models.IntegerField(default=0)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tahsilat_sorgulari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahsilat Sorgusu",
                "verbose_name_plural": "Tahsilat Sorguları",
                "ordering": ["-sorgu_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="TahsilatOzeti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ana_para_borc",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Toplam ana para borç",
                        max_digits=15,
                    ),
                ),
                (
                    "yapilan_toplam_tahsilat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Toplam yapılan tahsilat",
                        max_digits=15,
                    ),
                ),
                (
                    "toplam_kalan_anapara_borc",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Toplam kalan ana para borç",
                        max_digits=15,
                    ),
                ),
                ("sonuc_kodu", models.CharField(help_text="Sonuç kodu", max_length=10)),
                (
                    "sonuc_aciklamasi",
                    models.CharField(help_text="Sonuç açıklaması", max_length=200),
                ),
                (
                    "tahsilat_sorgu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ozet",
                        to="tahsilat.tahsilatsorgu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahsilat Özeti",
                "verbose_name_plural": "Tahsilat Özetleri",
            },
        ),
        migrations.CreateModel(
            name="TahsilatKaydi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tahsilat_id",
                    models.IntegerField(
                        help_text="DSİ API'den gelen tahsilat ID", unique=True
                    ),
                ),
                (
                    "tahakkuk_no",
                    models.CharField(help_text="Tahakkuk numarası", max_length=50),
                ),
                (
                    "gelir_turu",
                    models.CharField(help_text="Gelir türü", max_length=200),
                ),
                ("borcun_konusu", models.TextField(help_text="Borçun konusu")),
                ("cari_id", models.IntegerField(help_text="Cari ID")),
                (
                    "ana_para_borc",
                    models.DecimalField(
                        decimal_places=2, help_text="Ana para borç", max_digits=15
                    ),
                ),
                (
                    "yapilan_toplam_tahsilat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yapılan toplam tahsilat",
                        max_digits=15,
                    ),
                ),
                (
                    "kalan_anapara_borc",
                    models.DecimalField(
                        decimal_places=2, help_text="Kalan ana para borç", max_digits=15
                    ),
                ),
                ("tahakkuk_donemi", models.DateTimeField(help_text="Tahakkuk dönemi")),
                ("harici_id", models.IntegerField(help_text="Harici sistem ID")),
                (
                    "sorgu_tarihi",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Sorgu tarihi"
                    ),
                ),
                ("son_guncelleme", models.DateTimeField(auto_now=True)),
                (
                    "aktif",
                    models.BooleanField(default=True, help_text="Kayıt aktif mi"),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tahsilat_kayitlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahsilat Kaydı",
                "verbose_name_plural": "Tahsilat Kayıtları",
                "ordering": ["-tahakkuk_donemi"],
                "indexes": [
                    models.Index(
                        fields=["tahsilat_id"], name="tahsilat_ta_tahsila_445bc1_idx"
                    ),
                    models.Index(
                        fields=["tahakkuk_no"], name="tahsilat_ta_tahakku_f9f9b0_idx"
                    ),
                    models.Index(
                        fields=["kullanici", "tahakkuk_donemi"],
                        name="tahsilat_ta_kullani_287a1d_idx",
                    ),
                ],
            },
        ),
    ]
