# Generated by Django 4.2.7 on 2025-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahsilatkaydi',
            name='tahakkuk_donemi',
            field=models.DateTimeField(blank=True, help_text='Tahakkuk dönemi', null=True),
        ),
    ]
